Containers:
  - Name: OVMSClient
    DockerImage: ubuntu:22.04
    EnvironmentVariableFiles: test.env
    Entrypoint: /test-profile/entrypoint.sh
    Volumes: 
      - /test-profile:/test-profile
  - Name: OVMSServer
    DockerImage: ubuntu:22.04
    EnvironmentVariableFiles: test.env
    Entrypoint: /test-profile/entrypoint.sh
    Volumes: 
      - /test-profile:/test-profile
