Containers:
  - Name: Client
    DockerImage: test:dev
    EnvironmentVariableFiles: profile.env
    Entrypoint: /script/entrypoint.sh
    Volumes: 
      - ./test-profile:/test-profile
  - Name: Server
    DockerImage: test:dev
    EnvironmentVariableFiles: profile2.env
    Entrypoint: /script/entrypoint2.sh
    Volumes: 
      - ./test-profile:/test-profile
